-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 17:59:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventario` ;

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`desercion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`desercion` (
  `id_desercion` INT(11) NOT NULL,
  `cod_semestre` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `desercion_m` INT(11) NOT NULL,
  `desercion_h` INT(11) NOT NULL,
  `motivos_desercion` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`eficiencia_terminal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`eficiencia_terminal` (
  `id_eficiencia` INT(11) NOT NULL,
  `cod_semestre` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `eficiencia_m` INT(11) NOT NULL,
  `eficiencia_h` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`especialidad` (
  `id_especialidad` INT(11) NOT NULL,
  `cod_susbsistema` INT(11) NOT NULL,
  `nombre_especialidad` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`infraestructura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`infraestructura` (
  `id_inventario` INT(11) NOT NULL,
  `ciclo_escolar` INT(11) NOT NULL,
  `cod_institucion` INT(11) NOT NULL,
  `administracion` INT(11) NOT NULL,
  `direccion` INT(11) NOT NULL,
  `prefectura` INT(11) NOT NULL,
  `aulas` INT(11) NOT NULL,
  `aulas_artisticas` INT(11) NOT NULL,
  `sillas_aulas` INT(11) NOT NULL,
  `capacidad_alumnos_matutino` INT(11) NOT NULL,
  `capacidad_alumnos_vespertino` INT(11) NOT NULL,
  `bilbliotecas` INT(11) NOT NULL,
  `laboratorios` INT(11) NOT NULL,
  `sala_maestros` INT(11) NOT NULL,
  `cooperativa` INT(11) NOT NULL,
  `estacionamiento` INT(11) NOT NULL,
  `rampas_discapacidad` INT(11) NOT NULL,
  `sillas` INT(11) NOT NULL,
  `proyeccion_crecimiemto` FLOAT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`instituciones` (
  `id_institucion` INT(11) NOT NULL,
  `nombre_institucion` TEXT NOT NULL,
  `cod_subsistema` INT(11) NOT NULL,
  `cod_especialidad` TEXT NOT NULL,
  `modalidad` TEXT NOT NULL,
  `alumnos_registrados` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`matricula_inicial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`matricula_inicial` (
  `id_inicial` INT(11) NOT NULL,
  `cod_semestre` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `inicial_m` INT(11) NOT NULL,
  `inicial_h` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`matricula_termino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`matricula_termino` (
  `id_terminio` INT(11) NOT NULL,
  `cod_semestre` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `termino_m` INT(11) NOT NULL,
  `termino_h` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`reprobados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`reprobados` (
  `id_reprobados` INT(11) NOT NULL,
  `cod_semestre` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `reprobados_m` INT(11) NOT NULL,
  `reprobados_h` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `inventario`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`semestre` (
  `id_semestre` INT(11) NOT NULL,
  `cod_institucion` INT(11) NOT NULL,
  `modalidad` TEXT NOT NULL,
  `periodo` TEXT NOT NULL,
  `cod_especialidad` INT(11) NOT NULL,
  `generacion` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`subsistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`subsistema` (
  `id_subsistema` INT(11) NOT NULL,
  `sistema_educativo` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`usuarios` (
  `id_usuario` INT(11) NOT NULL,
  `usuario` TEXT NOT NULL,
  `correo_electronico` TEXT NULL DEFAULT NULL,
  `contraseña` VARCHAR(250) NOT NULL,
  `rol_id` INT(11) NULL DEFAULT NULL,
  `cod_institucion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `inventario`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `rol_id` ON `inventario`.`usuarios` (`rol_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `inventario`.`vunerabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`vunerabilidad` (
  `id_vunerabilidad` INT(11) NOT NULL,
  `cod_semestre` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `vunerabilidad_m` INT(11) NOT NULL,
  `vunerabilidad_h` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `inventario`.`vunerabilidad_atendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`vunerabilidad_atendidos` (
  `id_atendidos` INT(11) NOT NULL,
  `cod_semestre` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `atentidos_m` INT(11) NOT NULL,
  `atentidos_h` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
